module.exports = [
  {
    id: 1,
    itemName: "Groceries",
    amount: 50,
    date: "02-28-2024",
    from: "Local Market",
    category: "Food",
    transactionType: "withdrawal",
  },
  {
    id: 2,
    itemName: "Gasoline",
    amount: 40,
    date: "02-27-2024",
    from: "Gas Station",
    category: "Transportation",
    transactionType: "withdrawal",
  },
  {
    id: 3,
    itemName: "Salary",
    amount: 2000,
    date: "02-25-2024",
    from: "Employer",
    category: "Income",
    transactionType: "deposit",
  },
  {
    id: 4,
    itemName: "Restaurant Dinner",
    amount: 60,
    date: "02-24-2024",
    from: "Fine Dining Restaurant",
    category: "Food",
    transactionType: "withdrawal",
  },
  {
    id: 5,
    itemName: "Savings Deposit",
    amount: 500,
    date: "02-23-2024",
    from: "Bank",
    category: "Savings",
    transactionType: "deposit",
  },
  {
    id: 6,
    itemName: "Pet Food",
    amount: 30,
    date: "02-22-2024",
    from: "Pet Store",
    category: "Pets",
    transactionType: "withdrawal",
  },
  {
    id: 7,
    itemName: "Movie Tickets",
    amount: 25,
    date: "02-21-2024",
    from: "Cinema",
    category: "Entertainment",
    transactionType: "withdrawal",
  },
  {
    id: 8,
    itemName: "Electricity Bill",
    amount: 70,
    date: "02-20-2024",
    from: "Utility Company",
    category: "Utilities",
    transactionType: "withdrawal",
  },
  {
    id: 9,
    itemName: "Internet Subscription",
    amount: 50,
    date: "02-19-2024",
    from: "Internet Provider",
    category: "Utilities",
    transactionType: "withdrawal",
  },
  {
    id: 10,
    itemName: "Books",
    amount: 20,
    date: "02-18-2024",
    from: "Bookstore",
    category: "Education",
    transactionType: "withdrawal",
  },
  {
    id: 11,
    itemName: "Phone Bill",
    amount: 45,
    date: "02-17-2024",
    from: "Telecom Company",
    category: "Utilities",
    transactionType: "withdrawal",
  },
  {
    id: 12,
    itemName: "Gym Membership",
    amount: 35,
    date: "02-16-2024",
    from: "Fitness Center",
    category: "Health",
    transactionType: "withdrawal",
  },
  {
    id: 13,
    itemName: "Clothing",
    amount: 75,
    date: "02-15-2024",
    from: "Retail Store",
    category: "Personal",
    transactionType: "withdrawal",
  },
  {
    id: 14,
    itemName: "Car Insurance",
    amount: 100,
    date: "02-14-2024",
    from: "Insurance Company",
    category: "Insurance",
    transactionType: "withdrawal",
  },
  {
    id: 15,
    itemName: "Vacation Expenses",
    amount: 300,
    date: "02-13-2024",
    from: "Travel Agency",
    category: "Travel",
    transactionType: "withdrawal",
  },
  {
    id: 16,
    itemName: "Birthday Gift",
    amount: 40,
    date: "02-12-2024",
    from: "Gift Shop",
    category: "Gifts",
    transactionType: "withdrawal",
  },
  {
    id: 17,
    itemName: "Home Repairs",
    amount: 200,
    date: "02-11-2024",
    from: "Contractor",
    category: "Home",
    transactionType: "withdrawal",
  },
  {
    id: 18,
    itemName: "Coffee",
    amount: 5,
    date: "02-10-2024",
    from: "Café",
    category: "Food",
    transactionType: "withdrawal",
  },
  {
    id: 19,
    itemName: "Medicine",
    amount: 15,
    date: "02-09-2024",
    from: "Pharmacy",
    category: "Health",
    transactionType: "withdrawal",
  },
  {
    id: 20,
    itemName: "Phone Upgrade",
    amount: 200,
    date: "02-08-2024",
    from: "Electronics Store",
    category: "Electronics",
    transactionType: "withdrawal",
  },
  {
    id: 21,
    itemName: "Donation",
    amount: 50,
    date: "02-07-2024",
    from: "Charity Organization",
    category: "Charity",
    transactionType: "withdrawal",
  },
  {
    id: 22,
    itemName: "Car Maintenance",
    amount: 80,
    date: "02-06-2024",
    from: "Auto Repair Shop",
    category: "Transportation",
    transactionType: "withdrawal",
  },
  {
    id: 23,
    itemName: "Haircut",
    amount: 25,
    date: "02-05-2024",
    from: "Barber Shop",
    category: "Personal",
    transactionType: "withdrawal",
  },
  {
    id: 24,
    itemName: "Magazine Subscription",
    amount: 10,
    date: "02-04-2024",
    from: "Publisher",
    category: "Entertainment",
    transactionType: "dwithdrawal",
  },
  {
    id: 25,
    itemName: "School Supplies",
    amount: 30,
    date: "02-03-2024",
    from: "Stationery Store",
    category: "Education",
    transactionType: "withdrawal",
  },
  {
    id: 26,
    itemName: "Bus Fare",
    amount: 10,
    date: "02-02-2024",
    from: "Public Transportation",
    category: "Transportation",
    transactionType: "withdrawal",
  },
  {
    id: 27,
    itemName: "Dental Checkup",
    amount: 90,
    date: "02-01-2024",
    from: "Dental Clinic",
    category: "Health",
    transactionType: "withdrawal",
  },
  {
    id: 28,
    itemName: "Music Streaming Subscription",
    amount: 15,
    date: "01-31-2024",
    from: "Streaming Service",
    category: "Entertainment",
    transactionType: "withdrawal",
  },
  {
    id: 29,
    itemName: "Home Internet Upgrade",
    amount: 60,
    date: "01-30-2024",
    from: "Internet Service Provider",
    category: "Utilities",
    transactionType: "withdrawal",
  },
  {
    id: 30,
    itemName: "Investment",
    amount: 1000,
    date: "01-29-2024",
    from: "Investment Firm",
    category: "Investment",
    transactionType: "deposit",
  },
];
