module.exports = [
  {
    id: 1,
    itemName: "Groceries",
    amount: 50,
    date: "2024-02-28",
    from: "Local Market",
    category: "Food",
    transactionType: "Withdrawal",
  },
  {
    id: 2,
    itemName: "Gasoline",
    amount: 40,
    date: "2024-02-27",
    from: "Gas Station",
    category: "Transportation",
    transactionType: "Withdrawal",
  },
  {
    id: 3,
    itemName: "Salary",
    amount: 2000,
    date: "2024-02-25",
    from: "Employer",
    category: "Income",
    transactionType: "Deposit",
  },
  {
    id: 4,
    itemName: "Restaurant Dinner",
    amount: 60,
    date: "2024-02-24",
    from: "Fine Dining Restaurant",
    category: "Food",
    transactionType: "Withdrawal",
  },
  {
    id: 5,
    itemName: "Savings Deposit",
    amount: 500,
    date: "2024-02-23",
    from: "Bank",
    category: "Savings",
    transactionType: "Deposit",
  },
  {
    id: 6,
    itemName: "Pet Food",
    amount: 30,
    date: "2024-02-22",
    from: "Pet Store",
    category: "Pets",
    transactionType: "Withdrawal",
  },
  {
    id: 7,
    itemName: "Movie Tickets",
    amount: 25,
    date: "2024-02-21",
    from: "Cinema",
    category: "Entertainment",
    transactionType: "Withdrawal",
  },
  {
    id: 8,
    itemName: "Electricity Bill",
    amount: 70,
    date: "2024-02-20",
    from: "Utility Company",
    category: "Utilities",
    transactionType: "Withdrawal",
  },
  {
    id: 9,
    itemName: "Internet Subscription",
    amount: 50,
    date: "2024-02-19",
    from: "Internet Provider",
    category: "Utilities",
    transactionType: "Withdrawal",
  },
  {
    id: 10,
    itemName: "Books",
    amount: 20,
    date: "2024-02-18",
    from: "Bookstore",
    category: "Education",
    transactionType: "Withdrawal",
  },
  {
    id: 11,
    itemName: "Phone Bill",
    amount: 45,
    date: "2024-02-17",
    from: "Telecom Company",
    category: "Utilities",
    transactionType: "Withdrawal",
  },
  {
    id: 12,
    itemName: "Gym Membership",
    amount: 35,
    date: "2024-02-16",
    from: "Fitness Center",
    category: "Health",
    transactionType: "Withdrawal",
  },
  {
    id: 13,
    itemName: "Clothing",
    amount: 75,
    date: "2024-02-15",
    from: "Retail Store",
    category: "Personal",
    transactionType: "Withdrawal",
  },
  {
    id: 14,
    itemName: "Car Insurance",
    amount: 100,
    date: "2024-02-14",
    from: "Insurance Company",
    category: "Insurance",
    transactionType: "Withdrawal",
  },
  {
    id: 15,
    itemName: "Vacation Expenses",
    amount: 300,
    date: "2024-02-13",
    from: "Travel Agency",
    category: "Travel",
    transactionType: "Withdrawal",
  },
  {
    id: 16,
    itemName: "Birthday Gift",
    amount: 40,
    date: "2024-02-12",
    from: "Gift Shop",
    category: "Gifts",
    transactionType: "Withdrawal",
  },
  {
    id: 17,
    itemName: "Home Repairs",
    amount: 200,
    date: "2024-02-11",
    from: "Contractor",
    category: "Home",
    transactionType: "Withdrawal",
  },
  {
    id: 18,
    itemName: "Coffee",
    amount: 5,
    date: "2024-02-10",
    from: "Café",
    category: "Food",
    transactionType: "Withdrawal",
  },
  {
    id: 19,
    itemName: "Medicine",
    amount: 15,
    date: "2024-02-09",
    from: "Pharmacy",
    category: "Health",
    transactionType: "Withdrawal",
  },
  {
    id: 20,
    itemName: "Phone Upgrade",
    amount: 200,
    date: "2024-02-08",
    from: "Electronics Store",
    category: "Electronics",
    transactionType: "Withdrawal",
  },
  {
    id: 21,
    itemName: "Donation",
    amount: 50,
    date: "2024-02-07",
    from: "Charity Organization",
    category: "Charity",
    transactionType: "Withdrawal",
  },
  {
    id: 22,
    itemName: "Car Maintenance",
    amount: 80,
    date: "2024-02-06",
    from: "Auto Repair Shop",
    category: "Transportation",
    transactionType: "Withdrawal",
  },
  {
    id: 23,
    itemName: "Haircut",
    amount: 25,
    date: "2024-02-05",
    from: "Barber Shop",
    category: "Personal",
    transactionType: "Withdrawal",
  },
  {
    id: 24,
    itemName: "Magazine Subscription",
    amount: 10,
    date: "2024-02-04",
    from: "Publisher",
    category: "Entertainment",
    transactionType: "Withdrawal",
  },
  {
    id: 25,
    itemName: "School Supplies",
    amount: 30,
    date: "2024-02-03",
    from: "Stationery Store",
    category: "Education",
    transactionType: "Withdrawal",
  },
  {
    id: 26,
    itemName: "Bus Fare",
    amount: 10,
    date: "2024-02-02",
    from: "Public Transportation",
    category: "Transportation",
    transactionType: "Withdrawal",
  },
  {
    id: 27,
    itemName: "Dental Checkup",
    amount: 90,
    date: "2024-02-01",
    from: "Dental Clinic",
    category: "Health",
    transactionType: "Withdrawal",
  },
  {
    id: 28,
    itemName: "Music Streaming Subscription",
    amount: 15,
    date: "2024-01-31",
    from: "Streaming Service",
    category: "Entertainment",
    transactionType: "Withdrawal",
  },
  {
    id: 29,
    itemName: "Home Internet Upgrade",
    amount: 60,
    date: "2024-01-30",
    from: "Internet Service Provider",
    category: "Utilities",
    transactionType: "Withdrawal",
  },
  {
    id: 30,
    itemName: "Investment",
    amount: 1000,
    date: "2024-01-29",
    from: "Investment Firm",
    category: "Investment",
    transactionType: "Deposit",
  },
];
